import Footer from "./Components/Footer";
import Header from "./Components/Header";
import "./globals.css";
import { CartProvider } from "./Components/Context/CartContext";

export const metadata = {
  title: "Fetching Data I",
  description: "Generated by Cecilia Perdomo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Para que se pueda acceder desde cualquier lugar */}
        <CartProvider> 
          <Header />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
